FROM rust:1.70.0 as builder

WORKDIR /ibeji
COPY . .

RUN apt-get update && apt-get install -y protobuf-compiler

RUN cargo build
#RUN cargo build --release

FROM debian:bullseye

WORKDIR /ibeji/target/debug
COPY --from=builder /ibeji/target/debug/agritechnica-provider* ./
COPY --from=builder /ibeji/config/agritechnica_provider_settings.yaml .

EXPOSE 4011

CMD ["./agritechnica-provider"]