@startuml

component "Digital Twin Consumer" {
}

component "Digital Twin App Server" {
  component "Digital Twin Graph Service" {
    interface "Digital Twin Graph Interface"
    interface "Respond Interface"
  }
  component "Digital Twin Registry Service" {
    interface "Digital Twin Registry Interface"
  }
}

component "Digital Twin Provider" {
  interface "Request Interface"
}

"Digital Twin Provider" -left-> "Digital Twin Registry Interface" : Register

"Digital Twin Consumer" -right-> "Digital Twin Graph Interface" : Find/Get/Set/Invoke

"Digital Twin Graph Service" -down-> "Digital Twin Registry Interface": FindByModelId

"Digital Twin Graph Service" -right-> "Request Interface": Ask

"Digital Twin Provider" -left-> "Respond Interface": Answer

@enduml
