@startuml

autonumber

participant "Digital Twin Consumer" as CONSUMER
participant "Digital Twin Graph" as DIGITAL_TWIN_GRAPH
participant "Digital Twin Registry" as DIGITAL_TWIN_REGISTRY
participant "Digital Twin Provider" as PROVIDER

CONSUMER -> DIGITAL_TWIN_GRAPH: Find(model_id: "dtmi:sdv:vehicle;1") - request

DIGITAL_TWIN_GRAPH -> DIGITAL_TWIN_REGISTRY: FindByModeld(model_id: "dtmi:sdv:vehcile;1") - request
note right
end note
DIGITAL_TWIN_GRAPH <- DIGITAL_TWIN_REGISTRY: FindByModelId - response
note left
end note

loop Iterate over the results from the FindByModelId call
DIGITAL_TWIN_GRAPH -> PROVIDER: Ask - Get
DIGITAL_TWIN_GRAPH -> PROVIDER: Ask - Get
DIGITAL_TWIN_GRAPH <- PROVIDER: Answer
DIGITAL_TWIN_GRAPH <- PROVIDER: Answer
end

CONSUMER <- DIGITAL_TWIN_GRAPH: Find - response
note left
end note

@enduml
