#
# In-Vehicle Digital Twin Service Settings
#

# The IP address and port number that the in-vehicle digital twin service listens on for digital twin requests.
# Example: "0.0.0.0:80"
invehicle_digital_twin_authority: "0.0.0.0:5010"
