# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.
# SPDX-License-Identifier: MIT

[package]
name = "ibeji-common"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
ibeji-common_test = { path = "../common-test" }