name: Install Rust Toolchain
description: |
  Installs the Rust toolchain.
  Relies on the fact that rustup show will install a toolchain. The installed version is based on a toolchain file, or stable if no such file is found.
inputs:
  components:
    description: A list of additional components to install
    required: false
    default: null
runs:
  using: "composite"
  steps:
    - name: Install Rust Toolchain
      # A note on using rustup show to do this (from https://rust-lang.github.io/rustup/overrides.html):
      #   To verify which toolchain is active, you can use rustup show,
      #   which will also try to install the corresponding toolchain if the current one has not been installed [...].
      #   (Please note that this behavior is subject to change, as detailed in issue #1397 [https://github.com/rust-lang/rustup/issues/1397].)
      run: rustup show
      shell: bash
    - name: Install Additional Components
      run: rustup component add ${{ inputs.components }}
      shell: bash
      if: ${{ inputs.components != null }}