@startuml

participant "In-Vehicle Digital Twin Service"
participant "Consumer"

"Consumer" -> "In-Vehicle Digital Twin Service" : FindById - request (id)
"In-Vehicle Digital Twin Service" --> "Consumer" : FindById - response (dtdl)

@enduml
