@startuml

autonumber

"Digital Twin Consumer" -> "In-Vehicle Digital Twin Service" : FindById("dtmi:sdv:HVAC:AmbientAirTemperature;1") - request
"Digital Twin Consumer" <- "In-Vehicle Digital Twin Service" : FindById - response
note left
entityAccessInfo:
{
    name: "AmbientAirTemperature"
    id: "dtmi:sdv:HVAC:AmbientAirTemperature;1"
    description: "The immediate surroundings air temperature (in Fahrenheit)."
    endpointInfoList: [
        {
            protocol: "grpc"
            operations: ["Get", "Invoke"]
            uri: "http://127.0.0.1:4000"
            context: "dtmi:sdv:HVAC:AmbientAirTemperature;1"
        }
    ]
}
end note

"Digital Twin Consumer" -> "Digital Twin Provider" : Get - request
note right
{
    entity_id: "dtmi:sdv:HVAC:AmbientAirTemperature;1"
    consumer_uri: "http://127.0.0.1:5000"
}
end note

"Digital Twin Consumer" <- "Digital Twin Provider" : Get - response

"Digital Twin Consumer" <- "Digital Twin Provider" : Publish - request
note left
{
    entity_id: "dtmi:sdv:HVAC:AmbientAirTemperature;1"
    value:
    {
        "AmbientAirTemperature": 77,
        "$metadata": {
            "$model": "dtmi:sdv:HVAC:AmbientAirTemperature;1"
        }

    }
}
end note

"Digital Twin Consumer" -> "Digital Twin Provider" : Publish - response

@enduml
