@startuml

frame "Digital Twin Consumer" {
}

frame "In-Vehicle Digital Twin Service" {
  interface "Digital Twin Interface"
}

frame "Digital Twin Provider" {
}

"Digital Twin Provider" --> "Digital Twin Interface" : Register

"Digital Twin Consumer" --> "Digital Twin Interface" : FindById

@enduml
