@startuml

frame "Consumer" {
  interface DigitalTwinConsumerInterface
}

frame "In-Vehicle Digital Twin Service" {
  interface DigitalTwinInterface
}

frame "Provider" {
  interface DigitalTwinProviderInterface
}

@enduml
